export const LOAD_SUBJECTS_SUCCESS = 'LOAD_SUBJECTS_SUCCESS';
export const LOAD_TUTORS_SUCCESS = 'LOAD_TUTORS_SUCCESS';
export const UPDATE_TUTOR_SUCCESS = 'UPDATE_TUTOR_SUCCESS';
export const CREATE_TUTOR_SUCCESS = 'CREATE_TUTOR_SUCCESS';